version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
